# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#ERROS DO CODIGO
#1- gerar funciona sem o chamar tela
from PyQt5 import uic,QtCore, QtGui, QtWidgets
import sys
import time


def chama_tela():
   
    segunda_tela.show()

def Quit():
    print('saindo...')
    exit("0")
def lerArquivo():
    arquivo=QtWidgets.QFileDialog.getOpenFileName()[0]
    with open(arquivo, 'r') as a:
        print(a.read)
 
#def verifica():
   # if(primeira_tela.pushButton_3.clicked.connect()==True):
        #print("pode apertar gerar")
   #else:
     #   print("ERRO")
    




app=QtWidgets.QApplication([])
primeira_tela=uic.loadUi("GUI.ui")
segunda_tela=uic.loadUi("segunda_tela.ui")
primeira_tela.pushButton_2.clicked.connect(Quit)
segunda_tela.pushButton.clicked.connect(Quit)
salvar=primeira_tela.pushButton_3.clicked.connect(lerArquivo)#SALVAR TEM O ARQUIVO 
primeira_tela.pushButton_3.clicked.connect(chama_tela)
primeira_tela.show()


#verifica()
#SEGUNDA_TELA


app.exec()


